### ISSUE TITLE
Single NEMid strand corrupted

### ISSUE THREAD

**Issue by 404Wolf** [NATuG3/NATuG3#36]
When making a junction that results in a strand that has only one NEMid, somehow NoneType objects end up in the strand (or something of the sort), which results in not being able to remake the strand/interact in other weird ways.

![bug](https://github.com/NATuG3/NATuG3/assets/108041238/5f1ea099-3301-4e18-9edb-eecfa71d77dd)

**Comment by 404Wolf** [comment]
`INFO:ui.panels.side_view.workers:Juncter mode was run.
Traceback (most recent call last):
  File "C:\Users\wolfm\Desktop\Projects\NATuG\NATuG3\ui\panels\side_view\panel.py", line 135, in _on_points_clicked
    {
  File "C:\Users\wolfm\Desktop\Projects\NATuG\NATuG3\ui\panels\side_view\workers.py", line 46, in juncter
    strands.conjunct(point, point.juncmate)
  File "C:\Users\wolfm\Desktop\Projects\NATuG\NATuG3\structures\strands\strands.py", line 745, in conjunct
    if (not NEMid1.junctable) or (not NEMid2.junctable):
                                      ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'junctable'`
